---
apiVersion: v1
kind: Pod
metadata:
  name: __NAME__
  namespace: __NAMESPACE__
  labels:
    role: external
spec:
  containers:
    - name: __NAME__
      image: julianknocke/containers:shell
      imagePullPolicy: Always
      stdin: true
      tty: true
      envFrom:
        - configMapRef:
            name: shared-dynamic-config
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 200m
          memory: 0.5Gi
