---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    deploymentName: "web"
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: web
  minReadySeconds: 4
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: web
          image: julianknocke/containers:web
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: "1"
            - name: MESSAGE
              value: "hello world!"
            - name: SLEEP_MAX
              value: "59"
            - name: KEEP_ALIVE
              value: "1"
            - name: PATH_PREFIX
              value: "/web"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /_system/alive
              port: 8080
          readinessProbe:
            exec:
              command: ["test", "-f", "/ready"]
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep", "4"]
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    deploymentName: "web"
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: web
  type: ClusterIP
